Zones = {"00-01":"Vacant Residential",
"00-02":"Vacant Residential Land - Condominium",
"00-03":"Vacant Residential Common Area",
"00-04":"Vacant Residential with extra feature",
"01-01":"Single Family",
"01-02":"House w/guest house",
"01-03":"(Extra Features Only) - Miscellaneous (Barn, Extra features)",
"01-04":"Townhome",
"01-05":"Single Family Zero Lot Line",
"01-06":"Attached 1-story",
"01-07":"Single Family - Group Home/ALF",
"02-01":"Manufactured/Modular Housing - Single",
"02-02":"Manufactured/Modular Housing - Double",
"02-03":"Manufactured/Modular Housing - Triple",
"02-04":"Manufactured/Modular Housing - Site Improvements Only",
"02-99":"Manufactured/Modular Housing not suitable for occupancy / Redevelopment",
"03-01":"Multi-family 10 to 49 units",
"03-02":"Multi-family 50 to 99 units",
"03-03":"Multi-family 100 units +",
"03-04":"Multi-family - Low Income Housing Tax Credit",
"03-05":"Low end housing (multiple parcels operating as one income producing property)",
"03-99":"Multi-family not suitable for occupancy / Redevelopment",
"04-01":"Condominium - Residential",
"04-02":"Condominium - Residential Single Family Home / Zero Lot",
"04-03":"Condominium - Manufactured Home",
"04-04":"Condominium - Timeshare / Interval Ownership",
"04-05":"Condominium - Limited Common Area",
"04-06":"Condominium - Association owned Common Area",
"04-28":"Condominium - Parking Space",
"04-99":"Condominium not suitable for occupancy / Redevelopment",
"05-01":"Cooperatives - Residential",
"05-02":"Cooperatives - Residential Single Family Home",
"05-03":"Cooperatives - Manufactured House - Single",
"05-04":"Cooperatives - Manufactured House - Double",
"05-05":"Cooperatives - Manufactured House - Triple",
"05-06":"Cooperatives - Manufactured Home",
"05-07":"Cooperatives - Limited Common Area",
"05-08":"Cooperatives - Association owned Common Area",
"05-99":"Cooperatives not suitable for occupancy / Redevelopment",
"06-01":"Retirement homes (not eligible for exemption under section)",
"06-99":"Retirement home facility not suitable for occupancy / Redevelopment",
"07-01":"Miscellaneous residential (migrant camp, boarding homes, etc,)",
"07-02":"Mics. value on separate folio (pool, cabanas, rec. bldgs. Tennis courts, etc.)",
"07-03":"Miscellaneous residential air rights",
"07-99":"Miscellaneous residential not suitable for occupancy / Redevelopment",
"08-01":"Duplex with Guest House",
"08-02":"Multi-family 2 units - Duplex",
"08-03":"Multi-family 3 units -Triplex",
"08-04":"Multi-family 4 units - Quadplex",
"08-05":"Multi-family 5 - 9 units",
"08-06":"Single Family House with 2 or more rental units",
"08-07":"Three or more Single Family Homes with 3 or more rental units",
"08-08":"Two or more Townhouses",
"08-09":"Two or more Manufactured Homes (not a park)",
"08-10":"Transitional Housing",
"08-11":"Low end housing (multiple parcels operating as one income producing property)",
"08-99":"Multi-family improvements not suitable for occupancy / Redevelopment",
"09-00":"Undefined - reserved for use by Department of Revenue only",
"09-01":"Miscellaneous residential (migrant camp, boarding homes, etc,)",
"09-02":"Mics. value on separate folio (pool, cabanas, rec. bldgs. Tennis courts, etc.)",
"09-03":"Miscellaneous residential air rights",
"09-28":"Miscellaneous residential parking garage",
"09-99":"Miscellaneous residential not suitable for occupancy / Redevelopment",
"10-01":"Vacant Commercial",
"10-02":"Vacant Commercial with extra feature",
"10-03":"Vacant Commercial Common Area",
"10-04":"Vacant Commercial Land - Condominium",
"10-05":"Vacant Land Under High Tension Wires Not Utility Owned",
"10-06":"Vacant Land Under High Tension Wires Utility Owned",
"11-01":"Retail Store - 1 unit",
"11-02":"Retail up to 4,999 sq. ft.",
"11-03":"Retail - 5,000 sq. ft. to 20,000 sq. ft.",
"11-04":"Condominium - Commercial Retail",
"11-05":"Retail greater than 20,000 sq. ft.",
"11-06":"Drug Store - free standing, not attached",
"11-07":"Discount Store (Brands mart, Best Buy, etc.)",
"11-08":"Warehouse Discount Store (Costco, BJ's, Sam's Club, etc.)",
"11-09":"Home Improvement Center (Home Depot, Lowe's etc.)",
"11-10":"Convenience Store",
"11-11":"Convenience Store with gas pumps",
"11-12":"Convenience Store with drive-thru",
"11-13":"Flea Market / Swap Meet",
"11-14":"Retail - prior residence",
"11-15":"Fitness Center",
"11-99":"Retail improvements not suitable for occupancy / Redevelopment",
"12-01":"Mixed store or office and residential",
"12-02":"Mixed store and office",
"12-03":"Mixed store and warehouse",
"12-04":"Miscellaneous mixed uses not included in other codes",
"12-05":"Office and Restaurant",
"12-06":"Apartment with Ground Floor Retail (multiple tenants on ground floor)",
"12-99":"Mixed use improvements not suitable for occupancy / Redevelopment",
"13-01":"Department Stores (Macy's, Sears, J.C. Penny, etc.)",
"13-02":"Discount Department Stores (Wal-Mart, Kmart, Target, etc.) *",
"13-03":"Super Discount Department Stores w/grocery (Wal-Mart, Kmart, Target, etc.)",
"13-99":"Department Stores not suitable for occupancy / Redevelopment",
"14-01":"Supermarkets",
"14-02":"Supermarkets (not chain)",
"14-99":"Supermarkets not suitable for occupancy / Redevelopment",
"15-01":"Regional Shopping Center",
"15-99":"Regional Shopping Center not suitable for occupancy / Redevelopment",
"16-01":"Shopping Center - Community",
"16-02":"Shopping Center - Neighborhood",
"16-99":"Shopping Center not suitable for occupancy / Redevelopment",
"17-01":"Office building - non professional, 1 story",
"17-02":"Office - modular building, 1 story",
"17-03":"Office building / warehouse, 1 story",
"17-04":"Condominium Office, 1 story",
"17-05":"Office building / retail, 1 story",
"17-06":"Office building - prior residence",
"17-07":"Office Complex, 1 story",
"17-08":"Post Office - Non Exempt",
"17-99":"Office improvements not suitable for occupancy / Redevelopment",
"18-01":"Office building, single tenant - 2 or more stories",
"18-02":"Office building, multi tenant - 2 or more stories",
"18-03":"Office building, multi story / tenant with bank on 1st floor",
"18-04":"Condominium Office, multi story",
"18-05":"Office building, multi story / tenant with retail on 1st floor",
"18-06":"Office building - multi story - prior residence",
"18-07":"Office building, multi story with warehouse",
"18-08":"Office Complex, multi story",
"18-99":"Office improvements not suitable for occupancy / Redevelopment",
"19-01":"Professional building - single tenant, 1 story",
"19-02":"Professional building - multi tenant, 1 story",
"19-03":"Professional building - single tenant, 2 or more stories",
"19-04":"Condominium Professional building",
"19-05":"Professional building - multi tenant, 2 or more stories",
"19-06":"Professional building - prior residence",
"19-07":"Professional office complex",
"19-08":"Day Care Center / Facility",
"19-09":"Day Care Center / Facility - prior residence",
"19-10":"Medical - Doctor / Dentist office",
"19-11":"Medical - Doctor / Dentist office - prior residence",
"19-12":"Veterinarian Office",
"19-13":"Veterinarian Office - prior residence",
"19-14":"Animal Hospital",
"19-15":"Animal Kennel",
"19-16":"Animal Hospital / Kennel - prior residence",
"19-17":"Radio or TV station",
"19-99":"Professional improvements not suitable for occupancy / Redevelopment",
"20-01":"Airports - Private",
"20-02":"Airports - Commercial",
"20-03":"Bus Terminals",
"20-04":"Condominium Marinas",
"20-05":"Condominium Boat Docks / Slips",
"20-06":"Dry Boat Storage",
"20-07":"Marina - repair facilities",
"20-08":"Marina - boat manufacturing",
"20-09":"Marina - mixed use (retail store/restaurants/docks)",
"20-10":"Marina - Yacht Club",
"20-11":"Marina - slips / rack storage",
"20-12":"Marina - slips / ground storage",
"20-13":"Marina - slips / boat sales",
"20-14":"Piers - Fishing",
"20-15":"Deeded Boat Slip",
"20-16":"Marina - extra features only/no bldg square footage",
"20-99":"Improvements not suitable for occupancy / Redevelopment",
"21-01":"Restaurants - non franchise",
"21-02":"Restaurants - franchise sit down (Olive Garden, Bennigans, Red Lobster, etc.)",
"21-03":"Restaurants - carryout / delivery only",
"21-04":"Restaurants - prior residence",
"21-05":"Cafeterias",
"21-06":"Restaurants - Converted Warehouse",
"21-99":"Restaurant improvements not suitable for occupancy / Redevelopment",
"22-01":"Restaurants - Fast Food, franchise",
"22-02":"Restaurants - Fast Food, non-franchise",
"22-03":"Restaurants, Drive in only",
"22-99":"Fast Food / Drive-in restaurant improvements not suitable for occupancy / Redevelopment",
"23-01":"Financial Institution",
"23-02":"Financial Institution - Branch Facility",
"23-03":"Financial Institution - Drive-In only",
"23-04":"Financial Institution - prior residence",
"23-99":"Financial Institution improvements not suitable for occupancy / Redevelopment",
"24-01":"Insurance company offices, single or multi story",
"24-02":"Insurance company offices, single or multi story - prior residence",
"24-99":"Insurance company office improvements not suitable for occupancy / Redevelopment",
"25-01":"Repair service shops (excluding automotive)",
"25-02":"Commercial Laundry / Dry Cleaner (not coin laundry)",
"25-03":"Laundromat / coin laundry",
"25-99":"Repair / Laundry improvements not suitable for occupancy / Redevelopment",
"26-01":"Service Station (with Auto Repair)",
"26-02":"Service Station (with small convenience store)",
"26-03":"Service Station (with tenant - Subway, Pizza Hut, etc.)",
"26-04":"Truck Stop",
"26-99":"Service facility / Truck Stop improvements not suitable for occupancy / Redevelopment",
"27-01":"Auto Dealership Sales / full service center",
"27-02":"Auto Dealership Sales / full service center with parking garage",
"27-03":"Used automobile sales, independent",
"27-04":"Garage / auto body / auto paint shop",
"27-05":"Truck sales / service",
"27-06":"Manufactured home sales",
"27-07":"RV sales / service",
"27-08":"Carwash (full service)",
"27-09":"Carwash ( self-service)",
"27-10":"Quick Lube facility",
"27-11":"Tire dealer sales / repair",
"27-12":"Farm and machinery sales / service",
"27-13":"Auto rental / leasing facilities",
"27-99":"Auto / Marine facility improvements not suitable for occupancy / Redevelopment",
"28-01":"Parking lot",
"28-02":"Parking garage",
"28-03":"Manufactured Home park",
"28-04":"RV park",
"28-05":"Individually Owned MHP",
"28-99":"Use code 28 improvements not suitable for occupancy / Redevelopment",
"29-01":"Wholesale outlets",
"29-02":"Produce house",
"29-03":"Manufacturing outlets",
"29-99":"Use code 29 improvements not suitable for occupancy / Redevelopment",
"30-01":"Florist",
"30-02":"Greenhouse",
"30-03":"Nursery (non-agricultural classification)",
"30-99":"Use code 30 improvements not suitable for occupancy / Redevelopment",
"31-01":"Theatre (drive-in)",
"31-02":"Stadium (not enclosed)",
"31-99":"Theatre / Stadium improvements not suitable for occupancy / Redevelopment",
"32-01":"Theatre (enclosed)",
"32-02":"Auditorium (enclosed)",
"32-99":"Theatre / Auditorium improvements not suitable for occupancy / Redevelopment",
"33-01":"Nightclubs",
"33-02":"Bars",
"33-03":"Yacht Clubs",
"33-04":"Tennis clubs",
"33-05":"Clubhouses",
"33-06":"Social clubs",
"33-99":"Use code 33 improvements not suitable for occupancy / Redevelopment",
"34-01":"Bowling alleys",
"34-02":"Skating rinks",
"34-03":"Pool / Billiard halls",
"34-04":"Enclosed arenas",
"34-05":"Enclosed Entertainment (Indoor - arcade, skating rink, pool hall, bowling alley, etc.)",
"34-99":"Use code 34 improvements not suitable for occupancy / Redevelopment",
"35-01":"Tourist attractions",
"35-02":"Permanent exhibits",
"35-03":"Entertainment facilities (mini golf, go-carts, etc.)",
"35-04":"Amusement parks",
"35-05":"Fairgrounds (privately owned)",
"35-99":"Use code 35 improvements not suitable for occupancy / Redevelopment",
"36-01":"Camps",
"36-99":"Camp improvements not suitable for occupancy / Redevelopment",
"37-01":"Race track - horse with casino",
"37-02":"Race track - dog with casino",
"37-03":"Race track - auto",
"37-04":"Jai-Alai Fronton",
"37-05":"Casino",
"37-99":"Use code 37 improvements not suitable for occupancy / Redevelopment",
"38-01":"Golf Course - Public, privately owned",
"38-02":"Golf Course - Private",
"38-03":"Golf Course - Municipal",
"38-04":"Golf Course - Executive",
"38-05":"Golf Course - Par Three",
"38-06":"Golf Driving Range",
"38-07":"Golf Course - Maint Shed / Whse",
"38-99":"Golf Course / Driving Range improvements not suitable for occupancy / Redevelopment",
"39-01":"Hotel - limited service with food",
"39-02":"Hotel - limited service without food",
"39-03":"Hotel - full service",
"39-04":"Hotel - suite / extended stay",
"39-05":"Condominium - hotel / motel",
"39-06":"Hotel - luxury resort",
"39-07":"Hotel - convention center, resort",
"39-08":"Motel - no restaurant",
"39-09":"Motel - with restaurant",
"39-10":"Bed and Breakfast",
"39-99":"Hotel / Motel improvements not suitable for occupancy / Redevelopment",
"40-01":"Vacant Industrial",
"40-02":"Vacant Industrial with extra features",
"40-03":"Vacant Industrial Common Area",
"40-04":"Vacant Industrial Land - Condominium",
"41-01":"Light Manufacturing",
"41-02":"Small Equipment Manufacturing",
"41-03":"Small Machine Shops",
"41-04":"Instrument Manufacturing",
"41-05":"Printing Plants",
"41-06":"Miscellaneous Industrial Facility",
"41-99":"Manufacturing improvements not suitable for occupancy / Redevelopment",
"42-01":"Heavy Industrial",
"42-02":"Heavy Equipment Manufacturing",
"42-03":"Large Machine Shops",
"42-04":"Foundries",
"42-05":"Steel Fabricating Plants",
"42-06":"Auto or Aircraft Plants",
"42-99":"Heavy Industrial improvements not suitable for occupancy / Redevelopment",
"43-01":"Lumber yards, Sawmills, Planing Mills",
"43-99":"Lumber Yard / Mill improvements not suitable for occupancy / Redevelopment",
"44-01":"Packing Plants",
"44-02":"Fruit and Vegetable Packing Plants",
"44-03":"Meat Packing Plants",
"44-99":"Packing Plant improvements not suitable for occupancy / Redevelopment",
"45-01":"Canneries",
"45-02":"Fruit and Vegetable processing",
"45-03":"Bottlers and Brewers",
"45-04":"Distillers",
"45-99":"Use code 45 improvements not suitable for occupancy / Redevelopment",
"46-01":"Food Processing",
"46-02":"Bakeries",
"46-03":"Candy Factories",
"46-04":"Potato Chip Factories",
"46-99":"Use code 46 improvements not suitable for processing / Redevelopment",
"47-01":"Mineral Plants",
"47-02":"Cement / Asphalt Plants",
"47-03":"Rock and Gravel Plants",
"47-04":"Refineries",
"47-99":"Use code 47 improvements not suitable for occupancy / Redevelopment",
"48-01":"Warehousing",
"48-02":"Warehouse - Mini Storage (open)",
"48-03":"Warehouse - Mini Storage ( enclosed)",
"48-04":"Warehouse - Metal",
"48-05":"Condominium - Warehouse",
"48-06":"Warehouse - Pre Fab",
"48-07":"Warehouse - Truck Terminal",
"48-08":"Warehouse - Distribution",
"48-09":"Warehouse - Flex",
"48-10":"Warehouse - Retail",
"48-11":"Warehouse - Cold Storage",
"48-12":"Warehouse - Utility Building",
"48-13":"Misc. value on separate folio i.e., fence, slab (not paving)",
"48-14":"Warehouse - Telecommunication Switch Station",
"48-99":"Warehouse improvements not suitable for occupancy / Redevelopment",
"49-01":"Open Storage - new and used building supplies",
"49-02":"Junk Yards",
"49-03":"Auto Wrecking",
"49-04":"Fuel Storage",
"49-05":"Equipment and Materials Storage",
"49-99":"Use code 49 improvements not suitable for occupancy / Redevelopment",
"50-01":"Improved Agriculture",
"50-02":"Improved Agriculture, curtilage with residence",
"50-03":"Improved Agriculture, curtilage with manufactured home",
"50-04":"Improved Agriculture, with manufactured home on personal property",
"50-05":"Improved Agriculture, with barn / garage",
"50-99":"Improved Agriculture not suitable for occupancy / Redevelopment",
"51-01":"Cropland Soil Capability Class I",
"51-02":"Cropland Soil Capability Class I with residence",
"51-03":"Cropland Soil Capability Class I with manufactured home",
"51-04":"Cropland Soil Capability Class I with manufactured home on personal property",
"51-05":"Cropland Soil Capability Class I with barn / garage",
"51-99":"Cropland Soil Capability Class I improvements not suitable for occupancy / Redevelopment",
"52-01":"Cropland Soil Capability Class II",
"52-02":"Cropland Soil Capability Class II with residence",
"52-03":"Cropland Soil Capability Class II with manufactured home",
"52-04":"Cropland Soil Capability Class II with manufactured home on personal property",
"52-05":"Cropland Soil Capability Class II with barn / garage",
"52-99":"Cropland Soil Capability Class II improvements not suitable for occupancy / Redevelopment",
"53-01":"Cropland Soil Capability Class III",
"53-02":"Cropland Soil Capability Class III with residence",
"53-03":"Cropland Soil Capability Class III with manufactured home",
"53-04":"Cropland Soil Capability Class III with manufactured home on personal property",
"53-05":"Cropland Soil Capability Class III with barn / garage",
"53-99":"Cropland Soil Capability Class III improvements not suitable for occupancy / Redevelopment",
"54-01":"Timberland - site index 90 & above",
"55-01":"Timberland - site index 80-89",
"56-01":"Timberland - site index 70-79",
"57-01":"Timberland - site index 60-69",
"58-01":"Timberland - site index 50-59",
"59-01":"Timberland not classified by site index to pines",
"60-01":"Grazing Land Soil Capability Class I",
"60-02":"Grazing Land Soil Capability Class I with residence",
"60-03":"Grazing Land Soil Capability Class I with manufactured home",
"60-04":"Grazing Land Soil Capability Class I with manufactured home on personal prop.",
"60-05":"Grazing Land Soil Capability Class I with barn / garage",
"60-99":"Grazing Land Soil Capability Class I improvements not suitable for occupancy / Redevelopment",
"61-01":"Grazing Land Soil Capability Class II",
"61-02":"Grazing Land Soil Capability Class II with residence",
"61-03":"Grazing Land Soil Capability Class II with manufactured home",
"61-04":"Grazing Land Soil Capability Class II with manufactured home on personal prop.",
"61-05":"Grazing Land Soil Capability Class II with barn / garage",
"61-99":"Grazing Land Soil Capability Class II improvements not suitable for occupancy / Redevelopment",
"62-01":"Grazing Land Soil Capability Class III",
"62-02":"Grazing Land Soil Capability Class III with residence",
"62-03":"Grazing Land Soil Capability Class III with manufactured home",
"62-04":"Grazing Land Soil Capability Class III with manufactured home on personal prop.",
"62-05":"Grazing Land Soil Capability Class III with barn / garage",
"62-99":"Grazing Land Soil Capability Class III improvements not suitable for occupancy / Redevelopment",
"63-01":"Grazing Land Soil Capability Class IV - cattle",
"63-02":"Grazing Land Soil Capability Class IV - cattle with residence",
"63-03":"Grazing Land Soil Capability Class IV - cattle with manufactured home",
"63-04":"Grazing Land Soil Capability Class IV - cattle with MH on personal prop.",
"63-05":"Grazing Land Soil Capability Class IV - cattle with barn / garage",
"63-06":"Grazing Land Soil Capability Class IV - horses",
"63-07":"Grazing Land Soil Capability Class IV - horses with residence",
"63-08":"Grazing Land Soil Capability Class IV - horses with manufactured home",
"63-09":"Grazing Land Soil Capability Class IV - horses with MH on personal prop.",
"63-10":"Grazing Land Soil Capability Class IV - horses with barn / garage",
"63-11":"Grazing Land Soil Capability Class IV - goats",
"63-12":"Grazing Land Soil Capability Class IV - goats with residence",
"63-13":"Grazing Land Soil Capability Class IV - goats with manufactured home",
"63-14":"Grazing Land Soil Capability Class IV - goats with MH on personal prop.",
"63-15":"Grazing Land Soil Capability Class IV - goats with barn / garage",
"63-16":"Grazing Land Soil Capability Class IV - sheep",
"63-17":"Grazing Land Soil Capability Class IV - sheep with residence",
"63-18":"Grazing Land Soil Capability Class IV - sheep with manufactured home",
"63-19":"Grazing Land Soil Capability Class IV - sheep with MH on personal prop.",
"63-20":"Grazing Land Soil Capability Class IV - sheep with barn / garage",
"63-99":"Grazing Land Soil Capability Class IV improvements not suitable for occupancy / Redevelopment",
"64-01":"Grazing Land Soil Capability Class V",
"64-02":"Grazing Land Soil Capability Class V with residence",
"64-03":"Grazing Land Soil Capability Class V with manufactured home",
"64-04":"Grazing Land Soil Capability Class V with manufactured home on personal prop.",
"64-05":"Grazing Land Soil Capability Class V with barn / garage",
"64-99":"Grazing Land Soil Capability Class V improvements not suitable for occupancy / Redevelopment",
"65-01":"Grazing Land Soil Capability Class VI",
"65-02":"Grazing Land Soil Capability Class VI with residence",
"65-03":"Grazing Land Soil Capability Class VI with manufactured home",
"65-04":"Grazing Land Soil Capability Class VI with MH on personal property",
"65-05":"Grazing Land Soil Capability Class VI with barn / garage",
"65-99":"Grazing Land Soil Capability Class VI improvements not suitable for occupancy / Redevelopment",
"66-01":"Orchard Groves",
"66-02":"Orchard Groves with residence",
"66-03":"Orchard Groves with manufactured home",
"66-04":"Orchard Groves with manufactured home on personal property",
"66-05":"Orchard Groves with barn / garage",
"66-99":"Orchard Groves improvements not suitable for occupancy / Redevelopment",
"67-01":"Poultry",
"67-02":"Poultry with residence",
"67-03":"Poultry with manufactured home",
"67-04":"Poultry with manufactured home on personal property",
"67-05":"Poultry with barn / garage",
"67-06":"Tropical Fish",
"67-07":"Tropical Fish with residence",
"67-08":"Tropical Fish with manufactured home",
"67-09":"Tropical Fish with manufactured home on personal property",
"67-10":"Tropical Fish with barn / garage",
"67-11":"Bees",
"67-12":"Bees with residence",
"67-13":"Bees with manufactured home",
"67-14":"Bees with manufactured home on personal property",
"67-15":"Bees with barn / garage",
"67-21":"Miscellaneous Agriculture",
"67-22":"Miscellaneous Agriculture with residence",
"67-23":"Miscellaneous Agriculture with manufactured home",
"67-24":"Miscellaneous Agriculture with manufactured home on personal property",
"67-25":"Miscellaneous Agriculture with barn / garage",
"67-99":"Use code 67 improvements not suitable for occupancy / Redevelopment",
"68-01":"Dairies, Feed Lots",
"68-02":"Dairies, Feed Lots with residence",
"68-03":"Dairies, Feed Lots with manufactured home",
"68-04":"Diaries, Feed Lots with manufactured home on personal property",
"68-05":"Dairies, Feed Lots with barn / garage",
"68-99":"Use code 68 improvements not suitable for occupancy / Redevelopment",
"69-01":"Ornamentals, miscellaneous agriculture",
"69-02":"Ornamentals, miscellaneous agriculture with residence",
"69-03":"Ornamentals, miscellaneous agriculture with manufactured home",
"69-04":"Ornamentals, miscellaneous agriculture with MH on personal property",
"69-05":"Ornamentals, miscellaneous agriculture with barn / garage",
"69-99":"Use code 69 improvements not suitable for occupancy / Redevelopment",
"70-01":"Vacant Institutional",
"70-02":"Vacant Institutional with extra features",
"71-01":"Churches",
"71-02":"Church with residence",
"71-03":"Church with parsonage",
"71-04":"Church Administration Building",
"71-05":"Church - recreational",
"71-99":"Church improvements not suitable for occupancy / Redevelopment",
"72-01":"School - private",
"72-02":"School - private, church owned",
"72-03":"College - private",
"72-04":"Day Care / Nursery",
"72-05":"Day Care / Nursery - prior residence",
"72-06":"Pre school - private",
"72-07":"Pre school - private - prior residence",
"72-08":"Fraternity or Sorority home",
"72-99":"School improvements not suitable for occupancy / Redevelopment",
"73-01":"Hospital - privately owned",
"73-02":"Hospital - Re-Hab",
"73-99":"Hospital improvements not suitable for occupancy / Redevelopment",
"74-01":"Homes for the aged",
"74-02":"Independent Living Facilities",
"74-03":"Assisted Living Facilities",
"74-04":"Assisted Living Facilities - prior residence",
"74-05":"Assisted Living Facilities - prior multi family",
"74-06":"Continuing Care Retirement Communities (CCRC's)",
"74-99":"Use code 74 improvements not suitable for occupancy / Redevelopment",
"75-01":"Orphanages",
"75-02":"Orphanages - prior residence",
"75-03":"Other non-profit or charitable services",
"75-04":"Residential HOA",
"75-05":"Condominium HOA",
"75-06":"Townhouse HOA",
"75-07":"Commercial / Industrial HOA",
"75-99":"Use code 75 improvements not suitable for occupancy / Redevelopment",
"76-01":"Mortuaries / Funeral Homes",
"76-02":"Cemeteries - privately owned",
"76-03":"Cemeteries - government owned",
"76-04":"Crematoriums",
"76-99":"Use code 76 improvements not suitable for occupancy / Redevelopment",
"77-01":"Clubs",
"77-02":"Lodges",
"77-03":"Union Halls",
"77-99":"Clubs / Lodges / Union Halls improvements not suitable for occupancy / Redevelopment",
"78-01":"Sanitariums",
"78-02":"Convalescent & Rest Homes",
"78-03":"Convalescent & Rest Homes - prior residence",
"78-04":"Nursing Homes",
"78-05":"Nursing Homes - prior residence",
"78-06":"Re-Hab Living Facilities",
"78-07":"Re-Hab Living Facilities - prior residence",
"78-99":"Use code 78 improvements not suitable for occupancy / Redevelopment",
"79-01":"Cultural organizations, facilities",
"79-99":"Cultural organizations, facilities improvements not suitable for occupancy / Redevelopment",
"80-01":"Vacant Governmental",
"80-02":"Vacant Governmental with extra features",
"81-01":"Military",
"82-01":"Forest, parks, recreational areas - Federal",
"82-02":"Forest, parks, recreational areas - State",
"82-03":"Forest, parks, recreational areas - County",
"82-04":"Forest, parks, recreational areas - Municipal",
"83-01":"Public Schools",
"83-02":"Public Schools - elementary",
"83-03":"Public Schools - middle",
"83-04":"Public Schools - high school",
"83-99":"Public Schools improvements not suitable for occupancy / Redevelopment",
"84-01":"Colleges",
"84-99":"College improvements not suitable for occupancy / Redevelopment",
"85-01":"Hospitals - municipal owned",
"85-02":"Hospitals - county owned",
"85-03":"Hospitals - state owned",
"85-04":"Hospitals - district owned",
"85-99":"Hospitals improvements not suitable for occupancy / Redevelopment",
"86-01":"County owned land - vacant (not included in other codes)",
"86-02":"County owned land - improved (not included in other codes)",
"86-03":"County Administration Bldg.",
"86-04":"County Public Works / Utility",
"86-05":"County Corrections Facility",
"86-06":"County Courthouse",
"86-07":"County Police / Fire Station",
"86-99":"County improvements not suitable for occupancy / Redevelopment",
"87-01":"State owned land - vacant (not included in other codes)",
"87-02":"State owned land - improved (not included in other codes)",
"87-03":"State Administration Bldg.",
"87-04":"State Public Works / Utility",
"87-05":"State Corrections Facility",
"87-99":"State improvements not suitable for occupancy / Redevelopment",
"88-01":"Federal owned land - vacant (not included in other codes)",
"88-02":"Federal owned land - improved (not included in other codes)",
"88-03":"Federal Administration Bldg.",
"88-04":"Federal Corrections Facility",
"88-05":"Federal Courthouse",
"88-06":"Post Office - Federal Owned",
"88-99":"Federal improvements not suitable for occupancy / Redevelopment",
"89-01":"Municipal owned land - vacant (not included in other codes)",
"89-02":"Municipal owned land - improved (not included in other codes)",
"89-03":"Municipal Administration Bldg.",
"89-04":"Municipal Public Works / Utility",
"89-05":"Municipal Police / Fire Station",
"89-06":"Post Office - Municipal Owned",
"89-99":"Municipal improvements not suitable for occupancy / Redevelopment",
"90-01":"Leasehold Interest Govt. prop -vacant (leased by a non-governmental lessee)",
"90-02":"Leasehold Interest Govt. prop.-improved (leased by a non-governmental lessee)",
"91-01":"Utility, gas companies - vacant",
"91-02":"Utility, gas companies - improved",
"91-03":"Utility, electric companies - vacant",
"91-04":"Utility, electric companies - improved",
"91-05":"Utility, telephone and telegraph - vacant",
"91-06":"Utility, telephone and telegraph - improved",
"91-07":"Locally Assessed Railroads",
"91-08":"Water and Sewer Service",
"91-09":"Pipelines",
"91-10":"Utility - canal",
"91-11":"Radio, television, cellular phone communication towers",
"91-99":"Use code 91 improvements not functional or suitable for occupancy / Redevelopment",
"92-01":"Mining lands, petroleum lands, gas lands",
"93-01":"Subsurface rights",
"94-01":"Right of Way - Street, Road, etc. - Public",
"94-02":"Right of Way - Street, Road, etc. - Private",
"94-03":"Right of Way - drainage / irrigation, water retention",
"94-04":"Conservation Easement",
"95-01":"Submerged Lands",
"95-02":"River / Canal",
"95-03":"Lakes",
"95-04":"Ponds",
"95-05":"Bay",
"96-01":"Environmentally sensitive land",
"96-02":"Sewage disposal",
"96-03":"Solid waste",
"96-04":"Borrow pit",
"96-05":"Drainage reservoirs",
"96-06":"Waste lands",
"96-07":"Marsh",
"96-08":"Sand dunes",
"96-09":"Swamps",
"96-10":"Composting",
"97-01":"Outdoor recreation or park land subject to classified use assessment",
"98-01":"Centrally assessed",
"99-01":"Acreage not zoned agriculture"}